from enum import Enum


class AgentRoles(Enum):
    SCIENTIST = """
    The "Scientist Agent" is responsible for leading the investigative work to generate hypotheses and discover attributes that explain the phenomenon under study. 
        The Scientist Agent analyzes the results provided by the Tester Agent and determines the focus of the investigation. Based on this focus, the Scientist Agent generates new hypotheses and guides the Extractor Agent in extracting relevant attributes from the patient records. 
        The Scientist Agent must ensure that the investigation remains aligned with the overall research goals and objectives.
    """

    EXTRACTOR = """
        The "Extractor Agent" is responsible for extracting relevant attributes from the raw data based on the focus area generated by the Scientist Agent. 
        The Extractor Agent must also ensure that the extraction process is efficient and that the extracted attributes are of high quality.
    """

    TESTER = """
        The "Tester Agent" is responsible for evaluating the quality of the attributes extracted by the Extractor Agent. 
        The Tester Agent uses a variety of statistical and machine learning techniques to assess the predictive power of the extracted attributes. 
        The Tester Agent provides detailed feedback to the Scientist Agent consisting of classification metrics such as accuracy, precision, recall, f1-score, and per-attribute entropy and a feature importance assessment.
        This feedback is crucial for guiding the Scientist Agent in refining the focus of the investigation and generating new hypotheses.
    """
